"""add ai policy settings columns

Revision ID: ddde0bb3d5da
Revises: fe22a33518fe
Create Date: 2026-03-19 22:43:12.362213
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddde0bb3d5da'
down_revision: Union[str, None] = 'fe22a33518fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_settings', sa.Column('allow_ai_cancel_draft', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('ai_settings', sa.Column('require_operator_for_edit', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('ai_settings', sa.Column('require_operator_for_returns', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('ai_settings', sa.Column('max_variants_in_reply', sa.Integer(), server_default=sa.text('5'), nullable=False))
    op.add_column('ai_settings', sa.Column('confirm_before_order', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('ai_settings', sa.Column('auto_handoff_on_profanity', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_settings', 'auto_handoff_on_profanity')
    op.drop_column('ai_settings', 'confirm_before_order')
    op.drop_column('ai_settings', 'max_variants_in_reply')
    op.drop_column('ai_settings', 'require_operator_for_returns')
    op.drop_column('ai_settings', 'require_operator_for_edit')
    op.drop_column('ai_settings', 'allow_ai_cancel_draft')
    # ### end Alembic commands ###
